chore: log error in handlePayloadTooBigError
I noticed the following error this morning:
Error: PUT /tasks/:taskId: status=500, response={"error":{"code":"server_error","message":"Cannot read properties of undefined (reading 'code')"}}
It looks like setting the task as failed/succeed fails but the error
doesn't have the shape we expect.
Adding a try/catch to log the error and let the execution continue and
log the setSucceed/setFailed error