fix: TypeError: request.headers.split is not a function (#1981)
undici version was bumped yesterday but the sentry lib version 7.105
doesn't support it. Bumping sentry to 7.106 where the issue was fixed.
https://github.com/getsentry/sentry-javascript/releases/tag/7.106.0
https://github.com/getsentry/sentry-javascript/pull/10938

## Checklist before requesting a review (skip if just adding/editing
APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is: