chore: log error in handlePayloadTooBigError (#2576)
I noticed the following error this morning when a runner send the output
of a task back to jobs:
Error: PUT /tasks/:taskId: status=500,
response={"error":{"code":"server_error","message":"Cannot read
properties of undefined (reading 'code')"}} It looks like setting the
task as failed/succeed fails but the error doesn't have the shape we
expect.
Adding a try/catch to log the error and let the execution continue and
log the setSucceed/setFailed error

## Issue ticket number and link

## Checklist before requesting a review (skip if just adding/editing
APIs & templates)
- [ ] I added tests, otherwise the reason is: 
- [ ] I added observability, otherwise the reason is:
- [ ] I added analytics, otherwise the reason is: