fix: TypeError: request.headers.split is not a function
undici version was bumped yesterday but the sentry lib version 7.105
doesn't support it. Bumping sentry to 7.106 where the issue was fixed.
https://github.com/getsentry/sentry-javascript/releases/tag/7.106.0
https://github.com/getsentry/sentry-javascript/pull/10938